import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { RxAvatar } from 'react-icons/rx';
import Loader from '../components/UI/Loader';
import { useEffect, useState } from 'react';
import SpotifyWebApi from 'spotify-web-api-node';

export default function Home() {
   const router = useRouter();
   const [search, setSearch] = useState('');
   const [searchResults, setSearchResults] = useState([]);
   const { status, data: session } = useSession({
      onUnauthenticated() {
         router.push('/auth/signin');
      },
   });
   const spotifyApi = new SpotifyWebApi({
      clientId: process.env.SPOTIFY_CLIENT_ID,
   });
   let accessToken;
   if (session) accessToken = session.accessToken;
   useEffect(() => {
      if (!accessToken) return;
      spotifyApi.setAccessToken(accessToken);
   }, [accessToken]);

   useEffect(() => {
      if (!search) return setSearchResults([]);
      if (!accessToken) return;
      console.log(spotifyApi);
      spotifyApi.searchTracks(search).then((res) => {
         setSearchResults(res);
      });
   }, [accessToken]);
   if (status === 'loading') {
      return <Loader />;
   }
   console.log(searchResults);

   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <main>
            <div>
               <RxAvatar></RxAvatar>
               <img src='' alt='' />
               <span>email: {session.user.email}</span>
            </div>
         </main>
      </div>
   );
}
